# Generated by Django 5.2.6 on 2025-09-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='kabbilesh', max_length=255)),
                ('Class', models.CharField(help_text='12th', max_length=100)),
                ('DOB', models.DateField(help_text='20/01/2008')),
                ('Age', models.CharField(help_text='15', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
