# Generated by Django 5.2.6 on 2025-09-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayapp', '0002_student_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField()),
                ('car_model', models.CharField()),
                ('release_date', models.DateField()),
                ('millage', models.IntegerField()),
                ('color', models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
